version: "3.8"
services:
  ubuntu:
    image: ubuntu:latest
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./src2:/app
    working_dir: /app
